### PR TITLE
Added PHP 7.4 and 4 architectures for Travis tests

### PR DESCRIPTION
**Pull request by ibrahimBeladi**
Added PHP 7.4 for Travis tests.
Added the following architectures
- amd64
- ppc64le
- s390x
- arm6

Specified Linux (default), and added windows (not yet supported) and osx (services are not supported); both are commented out for now.

-----------------------
For PHP 7.4 on AMD64, there was an error:
> `webfiori\tests\entity\LanguageTest::testLoadTranslation01`
> Cannot use "parent" when current class scope has no parent

### CODE REVIEW

**Comment by usernane** [comment]
Since PHP 5.6 is not supported on arm64 and s360, the two architectures will be not included. ppc64le seems has an issue with SMTP connection which can be checked later.

**Comment by usernane** [comment]
Added support for PHP 7.4

**Comment by ibrahimBeladi** [comment]
I have excluded arm64 and s360 architectures on PHP 5.4.

**Comment by ibrahimBeladi** [comment]
Now, it is save to merge. It will do the tests without failing the overall test if the non-amd64 architectures fail.

**Pull request merged**
